/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steganografiasupdf.estrazione;

import steganografiasupdf.FramePrincipale;

/**
 *
 * @author Rocchina
 */
public class PannelloEstrazione extends javax.swing.JPanel {

    /**
     * Creates new form PannelloEstrazione
     */
    
    private final FramePrincipale frame;
    
    public PannelloEstrazione(FramePrincipale frame){
        this.frame = frame;
        initComponents();
        postInizializza();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApriPdf = new javax.swing.JButton();
        jTextFieldPdfSelezionato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessEstratto = new javax.swing.JTextArea();
        jButtonEstraiMess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButtonApriPdf.setText("Apri");

        jTextFieldPdfSelezionato.setText("Seleziona PDF");

        jTextAreaMessEstratto.setColumns(20);
        jTextAreaMessEstratto.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMessEstratto);

        jButtonEstraiMess.setText("Estrai Messaggio");

        jLabel1.setText("Messaggio estratto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPdfSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEstraiMess)
                            .addComponent(jButtonApriPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApriPdf)
                    .addComponent(jTextFieldPdfSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEstraiMess)
                        .addGap(83, 83, 83))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApriPdf;
    private javax.swing.JButton jButtonEstraiMess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMessEstratto;
    private javax.swing.JTextField jTextFieldPdfSelezionato;
    // End of variables declaration//GEN-END:variables

    private void postInizializza() {
        //inizializza le azioni nei bottoni
        this.jButtonApriPdf.setAction(this.frame.getSteganografia().getApriEstrazione());
        this.jButtonEstraiMess.setAction(this.frame.getSteganografia().getEstraiMess());
    }

    public void mostraPath(String pathFile) {
        this.jTextFieldPdfSelezionato.setText(pathFile);
    }
    
    public void setTesto(String messaggioEstratto){
        this.jTextAreaMessEstratto.setText(messaggioEstratto);
    }
}
