/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steganografiasupdf.embedding;

import steganografiasupdf.FramePrincipale;

/**
 *
 * @author Rocchina
 */
public class PannelloEmbedding extends javax.swing.JPanel {
    
    private final FramePrincipale frame;
    
    public PannelloEmbedding(FramePrincipale frame){
        this.frame = frame;
        initComponents();
        postInizializza();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldMessaggio = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jLabelSelezionaPDF = new javax.swing.JLabel();
        jButtonApri = new javax.swing.JButton();
        jButtonInserisciMess = new javax.swing.JButton();

        jLabel1.setText("Inserisci il messaggio:");

        jButtonOk.setText("OK");

        jLabelSelezionaPDF.setText("Seleziona PDF");

        jButtonApri.setText("Apri");

        jButtonInserisciMess.setText("Inserisci Messaggio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSelezionaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(jButtonApri))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInserisciMess, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldMessaggio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButtonOk)
                        .addGap(38, 38, 38)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelezionaPDF)
                    .addComponent(jButtonApri))
                .addGap(47, 47, 47)
                .addComponent(jButtonInserisciMess)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApri;
    private javax.swing.JButton jButtonInserisciMess;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSelezionaPDF;
    private javax.swing.JTextField jTextFieldMessaggio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the frame
     */
    public FramePrincipale getFrame() {
        return frame;
    }

    private void postInizializza() {
        this.jButtonOk.setAction(this.frame.getSteganografia().getOk());
        this.jButtonApri.setAction(this.frame.getSteganografia().getApriEmbedding());
        this.jButtonInserisciMess.setAction(this.frame.getSteganografia().getInserisci());
    }
    
    public String getMessaggio(){
        return this.jTextFieldMessaggio.getText();
    }

    public void mostraPath(String pathFile) {
        this.jLabelSelezionaPDF.setText(pathFile);
    }

    public String getPathFile() {
        return this.jLabelSelezionaPDF.getText();
    }
}
